receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
  otlphttp/loki:
    logs_endpoint: "http://localhost:3100/otlp/v1/logs"
  otlp/tempo:
    endpoint: "0.0.0.0:4317"
service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [otlphttp/loki, debug]
    traces:
      receivers: [otlp]
      exporters: [otlp/tempo, debug]